# Generated by Django 5.2.4 on 2025-10-21 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_devicetoken'),
        ('accounts', '0006_update_user_roles'),
    ]

    operations = [
    ]
