# Generated by Django 3.2.20 on 2025-09-16 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_requests', '0002_documentrequestaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
