# Generated by Django 5.2.4 on 2025-09-21 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_requests', '0003_alter_documentrequest_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentrequest',
            options={'ordering': ('-requested_at',)},
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='receipt_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='receipts/'),
        ),
    ]
