# Generated by Django 5.2.4 on 2025-09-23 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_requests', '0004_alter_documentrequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrequest',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
