# Generated by Django 5.2.4 on 2025-10-07 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_requests', '0005_documentrequest_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrequest',
            name='document',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='payment',
            field=models.BooleanField(default=False),
        ),
    ]
