# Generated by Django 5.2.4 on 2025-10-07 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_requests', '0010_alter_documentrequest_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrequestaction',
            name='document',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documentrequestaction',
            name='payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='documentrequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('confirming', 'Confirming'), ('awaiting_payment', 'Awaiting Payment'), ('pending', 'Pending'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected'), ('ready_to_claim', 'Ready to Claim'), ('on_process', 'On Process')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='AIChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation_id', models.CharField(max_length=100, unique=True)),
                ('session', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirming', 'Confirming'), ('awaiting_payment', 'Awaiting Payment'), ('pending', 'Pending'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected'), ('ready_to_claim', 'Ready to Claim'), ('on_process', 'On Process')], default='draft', max_length=20)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_histories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
