# Generated by Django 5.2.4 on 2025-10-12 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_requests', '0011_documentrequestaction_document_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AIChatHistory',
        ),
    ]
