# Generated by Django 5.2.4 on 2025-10-12 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_requests', '0013_unique_draft_constraint'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='documentrequest',
            name='unique_draft_per_student_type',
        ),
    ]
