# Generated by Django 5.2.4 on 2025-10-12 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_requests', '0014_remove_documentrequest_unique_draft_per_student_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrequest',
            name='receipt_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
