# Generated by Django 5.2.4 on 2025-10-12 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_requests', '0015_documentrequest_receipt_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentrequestaction',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('submitted', 'Submitted'), ('payment_method_set', 'Payment Method Set'), ('receipt_submitted', 'Receipt Submitted (Bypass)'), ('receipt_uploaded', 'Receipt Uploaded'), ('status_changed', 'Status Changed'), ('scheduled', 'Scheduled'), ('updated', 'Updated')], max_length=32),
        ),
    ]
