# Generated by Django 5.2.4 on 2025-10-17 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_requests', '0016_alter_documentrequestaction_action'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentrequestaction',
            options={'ordering': ('-response_time',)},
        ),
        migrations.RenameField(
            model_name='documentrequest',
            old_name='document_type',
            new_name='doc_type',
        ),
        migrations.RenameField(
            model_name='documentrequestaction',
            old_name='actor',
            new_name='faculty_id',
        ),
        migrations.RenameField(
            model_name='documentrequestaction',
            old_name='created_at',
            new_name='response_time',
        ),
        migrations.RemoveField(
            model_name='documentrequest',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='documentrequest',
            name='processed_by_id',
        ),
        migrations.RemoveField(
            model_name='documentrequestaction',
            name='action',
        ),
    ]
