# Generated by Django 5.2.4 on 2025-10-17 22:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_requests', '0017_alter_documentrequestaction_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentrequestaction',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RemoveField(
            model_name='documentrequest',
            name='doc_type',
        ),
        migrations.RemoveField(
            model_name='documentrequestaction',
            name='faculty_id',
        ),
        migrations.RemoveField(
            model_name='documentrequestaction',
            name='response_time',
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='document_type',
            field=models.CharField(choices=[('OTR', 'Official Transcript of Records'), ('COG', 'Certificate of Grades'), ('COE', 'Certificate of Enrollment'), ('OTHERS', 'Other Certifications')], default='OTR', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='processed_by_id',
            field=models.ForeignKey(blank=True, db_column='processed_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentrequestaction',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('submitted', 'Submitted'), ('payment_method_set', 'Payment Method Set'), ('receipt_submitted', 'Receipt Submitted (Bypass)'), ('receipt_uploaded', 'Receipt Uploaded'), ('status_changed', 'Status Changed'), ('scheduled', 'Scheduled'), ('updated', 'Updated')], default='created', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documentrequestaction',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentrequestaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
