# Generated by Django 5.2.4 on 2025-10-19 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_requests', '0018_alter_documentrequestaction_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentrequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('confirming', 'Confirming'), ('awaiting_payment', 'Awaiting Payment'), ('pending', 'Pending'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected'), ('ready_to_claim', 'Ready to Claim'), ('on_process', 'On Process'), ('claimed', 'Claimed')], default='draft', max_length=20),
        ),
    ]
