# Generated by Django 5.2.4 on 2025-10-20 12:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_requests', '0019_alter_documentrequest_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='documentrequest',
            constraint=models.UniqueConstraint(fields=('student_id', 'document_type', 'purpose'), name='unique_document_request_per_student_doc_purpose'),
        ),
    ]
