# Generated by Django 5.2.4 on 2025-10-12 03:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointmentaction'),
        ('document_requests', '0011_documentrequestaction_document_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='document_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='document_requests.documentrequest'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('missed', 'Missed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointmentaction',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('status_changed', 'Status Changed'), ('assigned', 'Assigned Faculty'), ('scheduled', 'Scheduled')], max_length=32),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'scheduled')), fields=('document_request',), name='unique_scheduled_appointment_per_request'),
        ),
    ]
