# Generated by Django 5.2.4 on 2025-10-19 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_document_request_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_appointments_per_day', models.PositiveIntegerField(default=100, help_text='Maximum number of appointments that can be scheduled per day')),
                ('appointment_start_hour', models.PositiveIntegerField(default=9, help_text='Hour when appointments start (24-hour format)')),
                ('appointment_end_hour', models.PositiveIntegerField(default=17, help_text='Hour when appointments end (24-hour format)')),
                ('appointment_duration_minutes', models.PositiveIntegerField(default=15, help_text='Duration of each appointment in minutes')),
                ('advance_days', models.PositiveIntegerField(default=1, help_text='Number of days in advance to schedule appointments')),
                ('exclude_weekends', models.BooleanField(default=True, help_text='Whether to exclude weekends from scheduling')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Appointment Settings',
                'verbose_name_plural': 'Appointment Settings',
            },
        ),
    ]
