# Generated by Django 5.2.4 on 2025-10-19 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointmentsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('missed', 'Missed'), ('cancelled', 'Cancelled'), ('claimed', 'Claimed'), ('no_show', 'No Show'), ('rescheduled', 'Rescheduled')], default='pending', max_length=20),
        ),
    ]
