# Generated by Django 5.2.4 on 2025-10-22 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_alter_appointment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10)),
                ('start_time', models.TimeField(help_text='Start time (e.g., 09:00)')),
                ('end_time', models.TimeField(help_text='End time (e.g., 17:00)')),
                ('slots_per_hour', models.PositiveIntegerField(default=4, help_text='Number of appointment slots per hour')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this time slot is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['day', 'start_time'],
                'unique_together': {('day', 'start_time', 'end_time')},
            },
        ),
    ]
