# Generated by Django 5.2.4 on 2025-09-24 17:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_conversation_id_backfill'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='chathistory',
            index=models.Index(fields=['user', 'conversation_id'], name='ai_chathist_user_id_01d79e_idx'),
        ),
    ]
