# Generated by Django 5.2.4 on 2025-09-24 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_chathistory_ai_chathist_user_id_01d79e_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='session',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_chat_histories', to=settings.AUTH_USER_MODEL),
        ),
    ]
