# Generated by Django 5.2.4 on 2025-10-07 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0004_chathistory_session_alter_chathistory_history_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='status',
            field=models.CharField(default='draft', max_length=50),
        ),
    ]
