# Generated by Django 5.2.4 on 2025-10-12 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0007_auto_20251012_0014'),
        ('document_requests', '0014_remove_documentrequest_unique_draft_per_student_type'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='chathistory',
            name='ai_chathist_user_id_01d79e_idx',
        ),
        migrations.AlterUniqueTogether(
            name='chathistory',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='user_id',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='conversation_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='document_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_history', to='document_requests.documentrequest'),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='history',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='session',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='status',
            field=models.CharField(default='draft', max_length=50),
        ),
    ]
