# Generated by Django 5.2.4 on 2025-10-17 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0008_remove_chathistory_ai_chathist_user_id_01d79e_idx_and_more'),
        ('document_requests', '0016_alter_documentrequestaction_action'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='chathistory',
            index=models.Index(fields=['user_id', '-updated_at'], name='ai_chathist_user_id_e62210_idx'),
        ),
        migrations.AddIndex(
            model_name='chathistory',
            index=models.Index(fields=['-updated_at'], name='ai_chathist_updated_63b73f_idx'),
        ),
    ]
