# Generated by Django 5.2.4 on 2025-10-17 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0008_remove_chathistory_ai_chathist_user_id_01d79e_idx_and_more'),
    ]

    operations = [
    ]
