# Generated by Django 5.2.4 on 2025-10-17 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0009_chathistory_ai_chathist_user_id_e62210_idx_and_more'),
        ('document_requests', '0017_alter_documentrequestaction_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='chathistory',
            name='ai_chathist_user_id_e62210_idx',
        ),
        migrations.RemoveIndex(
            model_name='chathistory',
            name='ai_chathist_updated_63b73f_idx',
        ),
        migrations.RemoveField(
            model_name='chathistory',
            name='session',
        ),
        migrations.RemoveField(
            model_name='chathistory',
            name='updated_at',
        ),
        migrations.AddIndex(
            model_name='chathistory',
            index=models.Index(fields=['user_id'], name='ai_chathist_user_id_92e172_idx'),
        ),
    ]
