# Generated by Django 5.2.4 on 2025-10-17 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0010_remove_chathistory_ai_chathist_user_id_e62210_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='chathistory',
            name='ai_chathist_user_id_92e172_idx',
        ),
        migrations.AddField(
            model_name='chathistory',
            name='session',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='chathistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
