# Generated by Django 5.2.4 on 2025-10-18 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0009_auto_20251018_0344'),
        ('ai', '0011_remove_chathistory_ai_chathist_user_id_92e172_idx_and_more'),
    ]

    operations = [
    ]
