# Generated by Django 5.2.4 on 2025-10-18 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0012_merge_20251018_0900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chathistory',
            name='user',
        ),
    ]
